### ISSUE TITLE
PROMETHEUS_CONTAINER_PORT not being correctly detected

### ISSUE THREAD

**Issue by splodgemcroo** [trallnag/prometheus-ecs-discoverer#5]
PROMETHEUS_CONTAINER_PORT environment variable not being correctly detected.  prometheus-ecs-discoverer incorrectly uses first container port, not the one specified by the environment variable in the task definiton.

Problem seems to be that the env var is being extracted from container not container_definition.

Pull request created with fixed version of code which is working in my environment :

https://github.com/trallnag/prometheus-ecs-discoverer/pull/4

**Comment by trallnag** [comment]
Thanks for raising and fixing the issue, @splodgemcroo. Sry for ignoring you for so long, I managed to disable notifications for my own project

**Comment by trallnag** [comment]
The bug never occurred in the prod env I'm using this project in because all the instrumented targets only ever have a single port open. And the "extract port" function falls back to the first port it finds in the network bindings if no port is configured explicitly. 

Your bugfix is now released with 3.2.1 (https://github.com/trallnag/prometheus-ecs-discoverer/releases/tag/releases%2F3.2.1)
